# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  name: wlx-ubuntu1804

resources:
  pipelines:
  - pipeline: Cypress-E2E-B2C-UI-Automation
    source: Woolworths.Frontend
    project: Trader
    trigger: 
      stages:
      - 'Deploy UAT AAE'

jobs:
  - job: Run-B2C-UI-E2E-Tests
    displayName: "Install Node.js and run B2C UI tests"
    pool:
      name: wlx-ubuntu1804
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Run B2C UI E2E Tests"
      - script: |
          npm install
          npm test -- --env tags=B2C-UI-E2E,fileConfig=b2c,otpValidationSwitch=true,creditCard='{"aa":"$(cc_number)","bb":"$(cc_cvv)","dd":"10","ee":"24","save":false,"verify":false}' --browser ${{ parameters.browser }}
        displayName: "Npm install and run B2C UI E2E tests"

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: "JUnit"
          testResultsFiles: "**/results-*.xml"
          testRunTitle: WOWE2EAPI-$(Build.BuildNumber)
          mergeTestResults: true
          searchFolder: "$(System.DefaultWorkingDirectory)/cypress/results"
        displayName: "Publish Test Results"