export const HomepageTopMenu = {
    ORDER_MANAGEMENT: 'ORDER_MANAGEMENT',
    SEARCH_MANAGEMENT: 'SEARCH_MANAGEMENT',
    INTEGRATION_MANAGEMENT: 'INTEGRATION_MANAGEMENT',
    IDENTITY_MANAGEMENT: 'IDENTITY_MANAGEMENT',
    B2B_MANAGEMENT: 'B2B_MANAGEMENT',
    SITE_MANAGEMENT: 'SITE_MANAGEMENT'
  }