export const paymentType = {
  CREDIT_CARD_ONLY: 'CREDIT_CARD_ONLY',
  PAYPAL_ONLY: 'PAYPAL_ONLY',
  CREDIT_CARD_PLUS_REWARDS: 'CREDIT_CARD_PLUS_REWARDS',
  PAYPAL_PLUS_REWARDS: 'PAYPAL_PLUS_REWARDS',
  PAYPAL_PLUS_REWARDS_PLUS_GIFTCARD: 'PAYPAL_PLUS_REWARDS_PLUS_GIFTCARD',
  CREDIT_CARD_PLUS_REWARDS_PLUS_GIFTCARD: 'CREDIT_CARD_PLUS_REWARDS_PLUS_GIFTCARD',
  GIFTCARD_ONLY: 'GIFTCARD_ONLY',
  PAYPAL_PLUS_GIFTCARD: 'PAYPAL_PLUS_GIFTCARD'
}
